Repository pknu-wap/StarList, pull requests merged in 2025-05, with the labels that each got.

#44 구글 로그인 / 익스텐션과 로그인 연동 구현완료
  client/src/App.jsx
  client/src/api/bookmarkApi.js
  client/src/assets/google.svg
  client/src/assets/logo.svg
  client/src/assets/main_text.svg
  client/src/assets/profile.svg
  client/src/assets/settings-icon.svg
  client/src/assets/title.svg
  client/src/components/bookmark/BookmarkGroupByDate.jsx
  client/src/components/common/header.jsx
  client/src/components/common/header/LogoStar.jsx
  client/src/components/common/header/NavBar.jsx
  client/src/components/common/header/NavLinks.jsx
  client/src/components/common/header/SettingsIcon.jsx
  client/src/components/common/header/UserIcon.jsx
  client/src/components/login/GoogleLoginButton.jsx
  client/src/index.css
  client/src/pages/AuthSuccessPage.jsx
  client/src/pages/CategoryPage.jsx
  client/src/pages/LoginPage.jsx
  client/src/pages/MainPage.jsx
  client/src/pages/RegisterPage.jsx
  client/src/pages/StartPage.jsx
  client/testCase.json
Labels: 🌕 프론트

#48 토큰을 client로 redirect하여 쿼리파마리터로 전송하도록 변경
  server/src/main/java/wap/starlist/config/auth/handler/OAuth2SuccessHandler.java
Labels: 👨🏻‍🌾 회원, 🔧 리팩터링, 🌑 백엔드

#51 로그인된 사용자의 동기화 여부를 확인할 수 있는 기능
  server/src/main/java/wap/starlist/config/auth/dto/UserInfoResponse.java
  server/src/main/java/wap/starlist/member/MemberController.java
  server/src/main/java/wap/starlist/member/MemberService.java
  server/src/main/java/wap/starlist/member/domain/Member.java
  server/src/main/java/wap/starlist/member/repository/MemberRepository.java
Labels: 👨🏻‍🌾 회원, 🥸 기능, 🌑 백엔드

#52 chore: LoginPage CSS 적용, 로고 이미지 추가, manifest 파일 수정
  extension/package.json
  extension/public/logo/logo.svg
  extension/public/logo/logo128.png
  extension/public/logo/logo16.png
  extension/public/logo/logo32.png
  extension/public/logo/logo48.png
  extension/public/logo/logo_temp.png
  extension/public/manifest.json
  extension/src/popup/App.css
  extension/src/popup/App.jsx
  extension/src/popup/components/Header.jsx
  extension/src/popup/components/LoginButton.jsx
  extension/src/popup/components/Logo.jsx
  extension/src/popup/components/ProfileButton.jsx
  extension/src/popup/components/Settings.jsx
  extension/src/popup/components/SettingsButton.jsx
  extension/src/popup/components/Text.jsx
  extension/src/popup/components/Userprofile.jsx
  extension/src/popup/main.jsx
  extension/src/popup/pages/LoginPage.jsx
  extension/src/service_worker/service_worker.js
  extension/yarn.lock
Labels: 🎨 디자인, ☀️ 익스텐션

#55 CORS 설정 추가
  server/src/main/java/wap/starlist/config/SecurityConfig.java
Labels: ☁️ 인프라, 🥸 기능, 🌑 백엔드

#19 BookmarkRepository의 기본 CRUD 유닛 테스트
  server/build.gradle
  server/src/main/java/wap/starlist/bookmark/service/BookmarkService.java
  server/src/test/java/wap/starlist/bookmark/repository/BookmarkRepositoryTest.java
  server/src/test/java/wap/starlist/bookmark/service/BookmarkServiceTest.java
  server/src/test/resources/application.yml
Labels: ✅ 테스트, 🔖 북마크, 🌑 백엔드

#60 익스텐션에서 전송한 BookmarkTreeNode를 저장하는 기능
  server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java
  server/src/main/java/wap/starlist/bookmark/domain/Bookmark.java
  server/src/main/java/wap/starlist/bookmark/domain/Folder.java
  server/src/main/java/wap/starlist/bookmark/domain/Root.java
  server/src/main/java/wap/starlist/bookmark/dto/request/BookmarkTreeNode.java
  server/src/main/java/wap/starlist/bookmark/repository/RootRepository.java
  server/src/main/java/wap/starlist/bookmark/service/BookmarkService.java
  server/src/main/java/wap/starlist/bookmark/service/FolderService.java
  server/src/main/java/wap/starlist/config/SecurityConfig.java
  server/src/main/java/wap/starlist/config/auth/JwtTokenProvider.java
  server/src/main/java/wap/starlist/config/auth/handler/OAuth2SuccessHandler.java
Labels: 🔖 북마크, 🥸 기능, 🌑 백엔드

#62 토큰을 사용하지 않았을 때 401상태를 보내도록 변경
  server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java
  server/src/main/java/wap/starlist/bookmark/domain/Bookmark.java
  server/src/main/java/wap/starlist/config/auth/AuthConstants.java
  server/src/main/java/wap/starlist/config/auth/JwtTokenProvider.java
  server/src/main/java/wap/starlist/config/auth/TokenAuthenticationFilter.java
  server/src/main/java/wap/starlist/config/auth/dto/SessionUser.java
  server/src/main/java/wap/starlist/member/MemberController.java
Labels: 👨🏻‍🌾 회원, 🔧 리팩터링, 🌑 백엔드

#65 리디렉트가 배포된 주소로 설정되어 로컬에서 로그인되지 않는 오류 해결
  server/src/main/java/wap/starlist/config/auth/handler/OAuth2SuccessHandler.java
Labels: 🌑 백엔드, ⚙️ 버그 수정

#64 이미 저장된 북마크가 있는 경우 저장된 시간 최신화
  server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java
  server/src/main/java/wap/starlist/bookmark/domain/Bookmark.java
  server/src/main/java/wap/starlist/bookmark/repository/BookmarkRepository.java
  server/src/main/java/wap/starlist/bookmark/service/BookmarkService.java
Labels: 🔖 북마크, 🥸 기능, 🌑 백엔드

#66 auth 패키지 구조 기능별로 구분되도록 변경
  server/src/main/java/wap/starlist/auth/JwtTokenProvider.java
  server/src/main/java/wap/starlist/auth/constants/AuthConstants.java
  server/src/main/java/wap/starlist/auth/dto/OAuth2UserPrincipal.java
  server/src/main/java/wap/starlist/auth/dto/UserInfoResponse.java
  server/src/main/java/wap/starlist/auth/dto/UserRole.java
  server/src/main/java/wap/starlist/auth/security/OAuth2SuccessHandler.java
  server/src/main/java/wap/starlist/auth/security/TokenAuthenticationFilter.java
  server/src/main/java/wap/starlist/auth/service/CustomOAuth2UserService.java
  server/src/main/java/wap/starlist/config/SecurityConfig.java
  server/src/main/java/wap/starlist/member/domain/Member.java
Labels: 🔧 리팩터링, 🌑 백엔드

#68 테스트 환경에서 oauth 관련 빈 생성이 이뤄지기 위해 환경변수 파일 추가
  server/.gitignore
  server/src/main/java/wap/starlist/bookmark/domain/Folder.java
  server/src/main/java/wap/starlist/bookmark/dto/request/BookmarkTreeNode.java
  server/src/main/java/wap/starlist/bookmark/service/BookmarkService.java
  server/src/test/java/wap/starlist/bookmark/service/BookmarkServiceTest.java
  server/src/test/resources/application.yml
Labels: ✅ 테스트, 🌑 백엔드, ⚙️ 버그 수정

#79 사용자와 관련된 모든 북마크를 가져오는 기능 추가
  server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java
  server/src/main/java/wap/starlist/bookmark/domain/Bookmark.java
  server/src/main/java/wap/starlist/bookmark/domain/Folder.java
  server/src/main/java/wap/starlist/bookmark/domain/Root.java
  server/src/main/java/wap/starlist/bookmark/dto/request/BookmarkTreeNode.java
  server/src/main/java/wap/starlist/bookmark/repository/RootRepository.java
  server/src/main/java/wap/starlist/bookmark/service/RootService.java
Labels: 🔖 북마크, 🥸 기능, 🌑 백엔드

#83 로그인 여부에 따른 라우팅 문제 해결
  client/src/pages/AuthSuccessPage.jsx
  client/src/store/useAuthStore.js
Labels: 🌕 프론트

#95 북마크 컴포넌트 추가완료
  client/.vscode.zip
  client/package-lock.json
  client/package.json
  client/postcss.config.js
  client/src/App.css
  client/src/App.jsx
  client/src/assets/icons/check-box-check.svg
  client/src/assets/icons/check-box-empty.svg
  client/src/assets/icons/check-box-hover.svg
  client/src/assets/icons/google.svg
  client/src/assets/icons/profile.svg
  client/src/assets/icons/settings-icon.svg
  client/src/assets/index.js
  client/src/assets/logo/logo.svg
  client/src/assets/react.svg
  client/src/assets/titles/main-text.svg
  client/src/assets/titles/title-main.svg
  client/src/assets/titles/title.svg
  client/src/components/bookmark/BookmarkCard.txt
  client/src/components/common/Header.jsx
  client/src/components/common/bookmark/BookmarkCard.jsx
  client/src/components/common/bookmark/BookmarkGroupByDate.jsx
  client/src/components/common/bookmark/BookmarkItem.jsx
  client/src/components/common/bookmark/TestBookmarkButton.jsx
  client/src/components/common/bookmark/ToggleButton.jsx
  client/src/components/common/header/Header.jsx
  client/src/components/common/header/LogoStar.jsx
  client/src/components/login/GoogleLoginButton.jsx
  client/src/index.css
  client/src/main.jsx
  client/src/pages/CategoryPage.jsx
  client/src/pages/MainPage.jsx
  client/src/pages/StartPage.jsx
  client/src/utils/groupBookmarksByDate.js
  client/styles/global.css
  client/tailwind.config.js
  client/vite.config.js
  client/yarn.lock
Labels: 🔖 북마크, 🌕 프론트

#101 ImageScraper로 웹페이지의 이미지를 가져와 저장
  server/build.gradle
  server/src/main/java/wap/starlist/bookmark/dto/request/BookmarkTreeNode.java
  server/src/main/java/wap/starlist/bookmark/service/BookmarkService.java
  server/src/main/java/wap/starlist/util/ImageScraper.java
Labels: 🔖 북마크, 🥸 기능, 🌑 백엔드

#102 Swagger 추가
  server/build.gradle
  server/src/main/java/wap/starlist/auth/security/TokenAuthenticationFilter.java
  server/src/main/java/wap/starlist/config/SwaggerConfig.java
Labels: 🖋️ 문서, 🌑 백엔드

#103 특정 폴더의 하위 노드를 가져오는 기능 추가
  server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java
  server/src/main/java/wap/starlist/bookmark/controller/FolderController.java
  server/src/main/java/wap/starlist/bookmark/dto/request/BookmarkTreeNode.java
  server/src/main/java/wap/starlist/bookmark/dto/response/BookmarkNodeResponse.java
  server/src/main/java/wap/starlist/bookmark/repository/FolderRepository.java
  server/src/main/java/wap/starlist/bookmark/service/BookmarkService.java
  server/src/main/java/wap/starlist/bookmark/service/FolderService.java
Labels: 🔖 북마크, 🥸 기능, 🌑 백엔드

#111 swagger에 접근할 때 로그인 없이 이용 가능
  server/src/main/java/wap/starlist/config/SecurityConfig.java
  server/src/main/java/wap/starlist/config/SwaggerConfig.java
Labels: 🥸 기능, 🌑 백엔드

#118 Feature/remainder UI
  client/package.json
  client/src/assets/buttons/arrow-left.svg
  client/src/assets/buttons/arrow-right.svg
  client/src/assets/index.js
  client/src/components/remainder/RemindCard.jsx
  client/src/components/remainder/RemindCarousel.jsx
  client/src/functions/hooks/useRemindBookmarks.js
  client/src/functions/utils/getRemindBookmarks.js
  client/src/main.jsx
  client/src/pages/MainPage.jsx
  client/tailwind.config.js
  client/yarn.lock
Labels: 🔖 북마크, 🌕 프론트

#120 지속해서 fetch 시도하는 문제 해결
  client/src/App.jsx
  client/src/components/remainder/RemindCarousel.jsx
  client/src/functions/hooks/useRemindBookmarks.js
  client/src/pages/MainPage.jsx
Labels: 🔖 북마크, 🌕 프론트

#126 최상위 폴더가 없는 경우 3001 에러 응답을 보내는 기능 추가
  server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java
  server/src/main/java/wap/starlist/bookmark/controller/FolderController.java
  server/src/main/java/wap/starlist/bookmark/service/FolderService.java
  server/src/main/java/wap/starlist/error/ErrorCode.java
  server/src/main/java/wap/starlist/error/ErrorResponse.java
  server/src/main/java/wap/starlist/error/GlobalExceptionHandler.java
  server/src/main/java/wap/starlist/error/exception/BaseException.java
  server/src/main/java/wap/starlist/error/exception/BookmarkNotFoundException.java
  server/src/main/java/wap/starlist/error/exception/NotFoundException.java
  server/src/main/java/wap/starlist/error/exception/TopFoldersNotFoundException.java
Labels: 🥸 기능, 🌑 백엔드

#130 북마크 dateLastUsed, syncing 필드를 채우도록 변경
  server/src/main/java/wap/starlist/bookmark/dto/request/BookmarkTreeNode.java
Labels: 🔖 북마크, 🔧 리팩터링, 🌑 백엔드

#140 폴더 구조를 반환하는 api 구현
  server/src/main/java/wap/starlist/bookmark/controller/FolderController.java
  server/src/main/java/wap/starlist/bookmark/dto/response/FolderTreeNode.java
  server/src/main/java/wap/starlist/bookmark/service/FolderService.java
Labels: 🔖 북마크, 🥸 기능, 🌑 백엔드

#141 chore: 리마인더 타이틀 위치 수정
  client/src/components/remainder/RemindCarousel.jsx
Labels: 🌕 프론트, 🎨 디자인

#152 CardList CSS, 클릭 처리 로직, 편집 모달창 추가
  client/.prettierrc
  client/src/assets/buttons/edit-icon.svg
  client/src/assets/cards/folder normal.svg
  client/src/assets/index.js
  client/src/components/cardlist/BookmarkCard.jsx
  client/src/components/cardlist/CardList.jsx
  client/src/components/cardlist/CardTitle.jsx
  client/src/components/cardlist/CardsContainer.jsx
  client/src/components/cardlist/EditModal.jsx
  client/src/components/cardlist/FolderCard.jsx
  client/src/components/cardlist/ToggleButton.jsx
  client/src/components/status/StatusView.jsx
  client/src/functions/hooks/useSelectedCardsStore.js
  client/src/functions/utils/ApiError.js
  client/src/functions/utils/fetchNodesByPath.js
  client/src/functions/utils/getRootNodes.js
  client/tailwind.config.js
Labels: 🥸 기능, 🌕 프론트

#153 스크랩한 이미지 URL을 클라이언트에게 전송하도록 수정
  server/src/main/java/wap/starlist/bookmark/dto/request/BookmarkTreeNode.java
  server/src/main/java/wap/starlist/bookmark/dto/response/BookmarkNodeResponse.java
  server/src/main/java/wap/starlist/bookmark/dto/response/SearchResponse.java
  server/src/main/java/wap/starlist/bookmark/service/BookmarkService.java
Labels: 🔖 북마크, 🔧 리팩터링, 🌑 백엔드

#161 검색결과를 하나의 리스트에 담아서 보내도록 변경
  server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java
  server/src/main/java/wap/starlist/bookmark/dto/response/SearchResponse.java
Labels: 🔖 북마크, 🔧 리팩터링, 🌑 백엔드

#165 검색 기능을 위한 훅 추가 및 적용
  client/src/components/cardlist/CardsContainer.jsx
  client/src/components/cardlist/FolderCard.jsx
  client/src/functions/hooks/useSearchNodes.js
  client/src/functions/hooks/useSearchStore.js
  client/src/functions/hooks/useSelectedCardsStore.js
  client/src/functions/utils/getNodesBySearch.js
Labels: 🥸 기능, 🌕 프론트

#164 리마인드 북마크 가져오는 API 추가
  server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java
  server/src/main/java/wap/starlist/bookmark/domain/Bookmark.java
  server/src/main/java/wap/starlist/bookmark/dto/request/ReminderBookmarkRequest.java
  server/src/main/java/wap/starlist/bookmark/dto/response/ReminderBookmarkErrorResponse.java
  server/src/main/java/wap/starlist/bookmark/dto/response/ReminderBookmarksResponse.java
  server/src/main/java/wap/starlist/bookmark/repository/BookmarkRepository.java
  server/src/main/java/wap/starlist/bookmark/service/BookmarkService.java
Labels: 🔖 북마크, 🥸 기능, 🌑 백엔드

#172 불필요한 import 제거
  server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java
Labels: 🔖 북마크, 🌑 백엔드, ⚙️ 버그 수정

#175 css 일부 수정 및 모달 관련 컴포넌트들 주석 추가
  client/src/components/cardlist/AddButton.jsx
  client/src/components/cardlist/AddSelectMenu.jsx
  client/src/components/cardlist/SearchBar.jsx
  client/src/components/modal/AddBookmarkModal.jsx
  client/src/components/modal/AddFolderModal.jsx
  client/src/components/modal/AddItemModal.jsx
  client/src/components/modal/DropDown.jsx
  client/tailwind.config.js
Labels: 🌕 프론트

#183 상단 이동 버튼 추가
  client/src/components/cardlist/ScrollToTopButton.jsx
  client/src/pages/MainPage.jsx
Labels: 🌕 프론트

#184 Stopwatch를 사용해 속도측정 후 로그 작성
  server/src/main/java/wap/starlist/bookmark/service/BookmarkService.java
Labels: 🔖 북마크, 🌑 백엔드

#186 북마크 동기화 속도 개선
  server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java
  server/src/main/java/wap/starlist/bookmark/domain/Bookmark.java
  server/src/main/java/wap/starlist/bookmark/domain/Folder.java
  server/src/main/java/wap/starlist/bookmark/dto/request/BookmarkTreeNode.java
  server/src/main/java/wap/starlist/bookmark/service/BookmarkService.java
Labels: 🔖 북마크, 🔧 리팩터링, 🌑 백엔드
