Repository pknu-wap/StarList, pull requests merged in 2025-06, with the labels that each got.

#189 og 태그가 붙은 이미지를 가져오도록 변경
  server/src/main/java/wap/starlist/bookmark/service/BookmarkService.java
  server/src/main/java/wap/starlist/util/ImageScraper.java
Labels: 🔖 북마크, 🔧 리팩터링, 🌑 백엔드

#192 여러 개의 북마크와 폴더를 이동할 수 있도록 변경
  server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java
  server/src/main/java/wap/starlist/bookmark/domain/Bookmark.java
  server/src/main/java/wap/starlist/bookmark/dto/request/BookmarkEditRequest.java
  server/src/main/java/wap/starlist/bookmark/dto/request/BookmarkMoveRequest.java
  server/src/main/java/wap/starlist/bookmark/repository/BookmarkRepository.java
  server/src/main/java/wap/starlist/bookmark/repository/FolderRepository.java
  server/src/main/java/wap/starlist/bookmark/service/BookmarkService.java
Labels: 🔖 북마크, 🔧 리팩터링, 🌑 백엔드

#199 리마인드 북마크를 보여주도록 변경
  server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java
  server/src/main/java/wap/starlist/bookmark/dto/request/BookmarkTreeNode.java
  server/src/main/java/wap/starlist/bookmark/repository/BookmarkRepository.java
  server/src/main/java/wap/starlist/bookmark/service/BookmarkService.java
  server/src/main/resources/application.yml
Labels: 🔖 북마크, 🔧 리팩터링, 🌑 백엔드

#200 리마인드 북마크에 이미지를 담도록 변경
  server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java
  server/src/main/java/wap/starlist/bookmark/domain/Bookmark.java
  server/src/main/java/wap/starlist/bookmark/dto/response/BookmarkResponse.java
  server/src/main/java/wap/starlist/bookmark/dto/response/ReminderBookmarksResponse.java
  server/src/main/java/wap/starlist/bookmark/service/BookmarkService.java
Labels: 🔖 북마크, 🔧 리팩터링, 🌑 백엔드

#206 폴더 생성시 googleId가 필수가 아니도록 변경
  server/src/main/java/wap/starlist/bookmark/domain/Folder.java
Labels: 🔖 북마크, 🔧 리팩터링, 🌑 백엔드

#208 사용자의 북마크 중에서 리마인드를 보여주도록 변경
  server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java
  server/src/main/java/wap/starlist/bookmark/domain/Bookmark.java
  server/src/main/java/wap/starlist/bookmark/repository/BookmarkRepository.java
  server/src/main/java/wap/starlist/bookmark/service/BookmarkService.java
  server/src/main/java/wap/starlist/error/ErrorCode.java
Labels: 🔖 북마크, 🔧 리팩터링, 🌑 백엔드

#210 리마인드 Api 관련 함수 복구
  client/src/functions/utils/getRemindBookmarks.js
Labels: 🔧 리팩터링, 🌕 프론트, ⚙️ 버그 수정

#212 chore:카드 리스트 최소 높이 지정
  client/src/components/cardlist/CardsContainer.jsx
  client/tailwind.config.js
Labels: 🌕 프론트, ⚙️ 버그 수정

#213 chore: gap 조절
  client/src/components/cardlist/CardsContainer.jsx
  client/tailwind.config.js
Labels: 🌕 프론트, ⚙️ 버그 수정

#215 chore:폴더 svg 수정
  client/src/assets/cards/folder-normal.svg
  client/src/components/cardlist/CardsContainer.jsx
  client/src/components/cardlist/FolderCard.jsx
  client/src/components/remainder/RemindCard.jsx
Labels: 🌕 프론트, ⚙️ 버그 수정

#216 chore:메인페이지 수정
  client/src/pages/MainPage.jsx
Labels: 🌕 프론트, ⚙️ 버그 수정

#219 캐러셀 css일부수정
  client/src/components/modal/AddItemModal.jsx
  client/src/components/remainder/RemindCard.jsx
  client/src/components/remainder/RemindCarousel.jsx
Labels: 🌕 프론트, 🎨 디자인

#223 feat:리마인드 제거 테스트
  client/src/components/remainder/RemindCard.jsx
  client/src/components/remainder/RemindCarousel.jsx
  client/src/functions/utils/patchRemindDisable.js
  client/src/pages/SettingPage.jsx
Labels: ✅ 테스트, 🔖 북마크, 🥸 기능, 🌕 프론트

#224 PATCH 요청이 cors가 발생하지 않도록 수정
  server/src/main/java/wap/starlist/config/SecurityConfig.java
Labels: 🌑 백엔드, ⚙️ 버그 수정

#226 chore: 리마인드 제거 api 관련 수정
  client/src/functions/utils/patchRemindDisable.js
Labels: 🌕 프론트, ⚙️ 버그 수정

#229 요청 dto를 받기 위해 @RequestBody 어노테이션 추가
  server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java
Labels: 🔖 북마크, 🌑 백엔드, ⚙️ 버그 수정

#230 chore:리마인드 제거 팝업 수정
  client/src/components/remainder/RemindCard.jsx
  client/src/functions/utils/getRemindBookmarks.js
Labels: 🌕 프론트, 🎨 디자인, ⚙️ 버그 수정

#233 리마인드 캐러셀 반응형 UI 적용
  client/src/assets/buttons/arrow-left.svg
  client/src/assets/buttons/arrow-right.svg
  client/src/assets/buttons/search.svg
  client/src/components/remainder/RemindCard.jsx
  client/src/components/remainder/RemindCarousel.jsx
  client/src/pages/MainPage.jsx
Labels: 🌕 프론트, 🎨 디자인

#236 캐러셀 오류 수정2
  client/src/components/remainder/RemindCarousel.jsx
  client/src/functions/utils/getRemindBookmarks.js
Labels: ⚙️ 버그 수정

#237 chore:비활성화한 북마크가 캐러셀에 제외하도록 함
  client/src/components/remainder/RemindCarousel.jsx
  client/src/functions/utils/getRemindBookmarks.js
Labels: 🌕 프론트, ⚙️ 버그 수정

#240 리마인드 북마크가 5개 이하인경우 무한히 증식하는 에러 수정(임시)
  client/src/components/remainder/RemindCarousel.jsx
Labels: 🌕 프론트, ⚙️ 버그 수정

#241 설정페이지 접근 막기
  client/src/components/header/Header.jsx
Labels: 🌕 프론트

#243 시작페이지 lazy 적용
  client/src/components/startPageComponents/Slider.jsx
  client/src/pages/StartPage.jsx
Labels: 🌕 프론트

#193 폴더 추가 API 수정
  server/src/main/java/wap/starlist/bookmark/controller/FolderController.java
  server/src/main/java/wap/starlist/bookmark/dto/request/FolderCreateRequest.java
  server/src/main/java/wap/starlist/bookmark/service/FolderService.java
Labels: 🔖 북마크, 🥸 기능, 🌑 백엔드
