Repository pknu-wap/StarList, pull requests merged in 2025-04, with the labels that each got.

#6 북마크 생성 기능 추가
  server/src/main/java/wap/starlist/controller/BookmarkController.java
  server/src/main/java/wap/starlist/domain/Bookmark.java
  server/src/main/java/wap/starlist/dto/request/BookmarkCreateRequest.java
  server/src/main/java/wap/starlist/dto/response/BookmarkErrorResponse.java
  server/src/main/java/wap/starlist/dto/response/BookmarkResponse.java
  server/src/main/java/wap/starlist/service/BookmarkService.java
  server/src/main/resources/application.properties
Labels: 🔖 북마크, 🥸 기능, 🌑 백엔드

#9 구글 로그인 기능 개발
  .github/pull_request_template.md
  server/.gitignore
  server/src/main/java/wap/starlist/controller/AuthController.java
  server/src/main/java/wap/starlist/controller/BookmarkController.java
  server/src/main/java/wap/starlist/domain/Bookmark.java
  server/src/main/java/wap/starlist/domain/Folder.java
  server/src/main/java/wap/starlist/domain/Member.java
  server/src/main/java/wap/starlist/domain/ParentType.java
  server/src/main/java/wap/starlist/domain/Root.java
  server/src/main/java/wap/starlist/dto/request/BookmarkCreateRequest.java
  server/src/main/java/wap/starlist/dto/response/BookmarkErrorResponse.java
  server/src/main/java/wap/starlist/dto/response/BookmarkResponse.java
  server/src/main/java/wap/starlist/repository/BookmarkRepository.java
  server/src/main/java/wap/starlist/repository/FolderRepository.java
  server/src/main/java/wap/starlist/repository/RootRepository.java
  server/src/main/java/wap/starlist/service/AuthService.java
  server/src/main/java/wap/starlist/service/BookmarkService.java
  server/src/main/resources/application.properties
Labels: 👨🏻‍🌾 회원, 🥸 기능, 🌑 백엔드

#16 docs: PR 템플릿에서 제목 삭제
  .github/pull_request_template.md
Labels: 🖋️ 문서

#18 OAuth를 활용한 구글 소셜 로그인 구현
  server/.gitignore
  server/build.gradle
  server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java
  server/src/main/java/wap/starlist/bookmark/domain/Bookmark.java
  server/src/main/java/wap/starlist/bookmark/domain/Folder.java
  server/src/main/java/wap/starlist/bookmark/domain/ParentType.java
  server/src/main/java/wap/starlist/bookmark/domain/Root.java
  server/src/main/java/wap/starlist/bookmark/dto/request/BookmarkCreateRequest.java
  server/src/main/java/wap/starlist/bookmark/dto/response/BookmarkErrorResponse.java
  server/src/main/java/wap/starlist/bookmark/dto/response/BookmarkResponse.java
  server/src/main/java/wap/starlist/bookmark/repository/BookmarkRepository.java
  server/src/main/java/wap/starlist/bookmark/repository/FolderRepository.java
  server/src/main/java/wap/starlist/bookmark/repository/RootRepository.java
  server/src/main/java/wap/starlist/bookmark/service/BookmarkService.java
  server/src/main/java/wap/starlist/config/SecurityConfig.java
  server/src/main/java/wap/starlist/config/auth/CustomOAuth2UserService.java
  server/src/main/java/wap/starlist/config/auth/OAuthConstants.java
  server/src/main/java/wap/starlist/config/auth/dto/GoogleProperties.java
  server/src/main/java/wap/starlist/config/auth/dto/GoogleUserInfo.java
  server/src/main/java/wap/starlist/config/auth/dto/OAuthAttributes.java
  server/src/main/java/wap/starlist/config/auth/dto/SessionUser.java
  server/src/main/java/wap/starlist/config/auth/dto/UserRole.java
  server/src/main/java/wap/starlist/controller/AuthController.java
  server/src/main/java/wap/starlist/domain/Member.java
  server/src/main/java/wap/starlist/member/controller/AuthController.java
  server/src/main/java/wap/starlist/member/domain/Member.java
  server/src/main/java/wap/starlist/member/repository/MemberRepository.java
  server/src/main/java/wap/starlist/member/service/AuthService.java
  server/src/main/java/wap/starlist/service/AuthService.java
  server/src/main/resources/application.properties
  server/src/main/resources/application.yml
Labels: 👨🏻‍🌾 회원, 🥸 기능, 🌑 백엔드

#14 폴더 생성 기능 개발
  server/src/main/java/wap/starlist/controller/FolderController.java
  server/src/main/java/wap/starlist/domain/Folder.java
  server/src/main/java/wap/starlist/dto/request/FolderCreateRequest.java
  server/src/main/java/wap/starlist/dto/response/FolderErrorResponse.java
  server/src/main/java/wap/starlist/dto/response/FolderResponse.java
  server/src/main/java/wap/starlist/service/FolderService.java
Labels: 🔖 북마크, 🥸 기능, 🌑 백엔드

#27 잘못 Merge된 코드 삭제
  server/src/main/java/wap/starlist/controller/FolderController.java
  server/src/main/java/wap/starlist/service/FolderService.java
Labels: 🌑 백엔드

#30 feat: 범용 컴포넌트 구현
  extension/src/popup/components/Logo.jsx
  extension/src/popup/components/Text.jsx
Labels: 🥸 기능, ☀️ 익스텐션

#31 develop 브랜치를 main에 merge
  server/src/main/java/wap/starlist/controller/FolderController.java
  server/src/main/java/wap/starlist/domain/Folder.java
  server/src/main/java/wap/starlist/dto/request/FolderCreateRequest.java
  server/src/main/java/wap/starlist/dto/response/FolderErrorResponse.java
  server/src/main/java/wap/starlist/dto/response/FolderResponse.java
  server/src/main/java/wap/starlist/service/FolderService.java
Labels: 🌑 백엔드

#37 feat: 로그인 요청/응답 기능 구현
  extension/.gitignore
  extension/public/manifest.json
  extension/src/popup/components/LoginButton.jsx
  extension/src/popup/hooks/useNavigation.js
  extension/src/popup/pages/LoginPage.jsx
  extension/src/service_worker/service_worker.js
Labels: 👨🏻‍🌾 회원, 🥸 기능, ☀️ 익스텐션

#32 폴더 삭제 기능 개발
  server/src/main/java/wap/starlist/controller/FolderController.java
  server/src/main/java/wap/starlist/service/FolderService.java
Labels: 🔖 북마크, 🌑 백엔드

#39 JWT 토큰 기반 로그인으로 변경
  server/build.gradle
  server/src/main/java/wap/starlist/config/SecurityConfig.java
  server/src/main/java/wap/starlist/config/auth/CustomOAuth2UserService.java
  server/src/main/java/wap/starlist/config/auth/JwtTokenProvider.java
  server/src/main/java/wap/starlist/config/auth/OAuthConstants.java
  server/src/main/java/wap/starlist/config/auth/TokenAuthenticationFilter.java
  server/src/main/java/wap/starlist/config/auth/dto/GoogleProperties.java
  server/src/main/java/wap/starlist/config/auth/dto/GoogleUserInfo.java
  server/src/main/java/wap/starlist/config/auth/dto/OAuth2UserPrincipal.java
  server/src/main/java/wap/starlist/config/auth/dto/UserInfoResponse.java
  server/src/main/java/wap/starlist/config/auth/handler/OAuth2SuccessHandler.java
  server/src/main/java/wap/starlist/config/auth/service/CustomOAuth2UserService.java
  server/src/main/java/wap/starlist/member/controller/AuthController.java
  server/src/main/java/wap/starlist/member/service/AuthService.java
Labels: 👨🏻‍🌾 회원, 🔧 리팩터링, 🌑 백엔드

#40 Folder 관련 기능을 Bookmark 패키지로 이동
  server/src/main/java/wap/starlist/bookmark/controller/FolderController.java
  server/src/main/java/wap/starlist/bookmark/domain/Folder.java
  server/src/main/java/wap/starlist/bookmark/dto/request/FolderCreateRequest.java
  server/src/main/java/wap/starlist/bookmark/dto/response/FolderErrorResponse.java
  server/src/main/java/wap/starlist/bookmark/dto/response/FolderResponse.java
  server/src/main/java/wap/starlist/bookmark/service/FolderService.java
  server/src/main/java/wap/starlist/domain/Bookmark.java
  server/src/main/java/wap/starlist/domain/Folder.java
  server/src/main/java/wap/starlist/domain/Member.java
  server/src/main/java/wap/starlist/domain/ParentType.java
  server/src/main/java/wap/starlist/domain/Root.java
  server/src/main/java/wap/starlist/repository/BookmarkRepository.java
  server/src/main/java/wap/starlist/repository/FolderRepository.java
  server/src/main/java/wap/starlist/repository/RootRepository.java
Labels: 🌑 백엔드

#42 feat: 동기화 시작 버튼 구현
  extension/public/manifest.json
  extension/src/popup/components/SyncButton.jsx
  extension/src/popup/hooks/useNavigation.js
  extension/src/popup/pages/SyncStartPage.jsx
  extension/src/popup/pages/SyncStatusPage.jsx
  extension/src/service_worker/service_worker.js
Labels: 🔖 북마크, 🥸 기능, ☀️ 익스텐션

#43 북마크 삭제 기능 구현
  server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java
  server/src/main/java/wap/starlist/bookmark/dto/request/BookmarksDeleteRequest.java
  server/src/main/java/wap/starlist/bookmark/dto/response/BookmarksDeleteErrorResponse.java
  server/src/main/java/wap/starlist/bookmark/dto/response/BookmarksDeleteResponse.java
  server/src/main/java/wap/starlist/bookmark/service/BookmarkService.java
Labels: 🔖 북마크, 🥸 기능, 🌑 백엔드
